### ISSUE TITLE
Can FilePart method accept InputStream or InputStreamSource in memory

### ISSUE THREAD

**Issue by shinux** [mizosoft/methanol#20]
Scenario:

I have a spring boot application which receive a form-data request with some files and I'll post those file to another web service. 

Due to methanol's `filePart` only receive file in type of file Path, so I have to save that file (Spring boot's MultipartFile extends from InputStreamSource ) into disk, then read it. And I though it may be redundant for me...so I'm looking for way to pass or regard input stream as file part.

Maybe it's not methanol's expected design or there is simple way to achieve what I want.

Any response is appreciated.🙏

**Comment by mizosoft** [comment]
Hi!

`filePart` is a convenient method for directly adding parts with `Path` sources. If you want to add a part with a filename (a file part) but from a different source, you can use [`MultlipartBodyPublisher.Builder::formPart`](https://mizosoft.github.io/methanol/1.x/doc/methanol/com/github/mizosoft/methanol/MultipartBodyPublisher.Builder.html#formPart(java.lang.String,java.lang.String,java.net.http.HttpRequest.BodyPublisher)) to directly add the part from a `BodyPublisher`.

 Considering your scenario, here's how you'd do it:
```java
InputStream in = ...
MultipartBodyPublisher body = MultipartBodyPublisher.newBuilder()
    .formPart("field_name", "file_name", BodyPublishers.ofInputStream(() -> in))
     ...
    .build();
```
Please tell me if that works for you. Thanks!

**Comment by shinux** [comment]
I thought it works to me, thanks for your prompt reply.
