### ISSUE TITLE
Enrich reported Progress in multipart upload request

### ISSUE THREAD

**Issue by nemphys** [mizosoft/methanol#23]
Currently, I can see that it is possible to attach a ProgressTracker to a MultPartBodyPublisher in order to track the progress of an upload, but the returned Progress object only contains the time/bytes information for the whole request.

This is fine for single-file upload requests, but if the request involves uploading multiple files, it would be nice to provide the current file information, along with a per file progress value.

**Comment by mizosoft** [comment]
Yes I believe this would be a nice enhancement to `ProgressTracker`. I'm guessing it won't be straightforward as hooks must be added to `MultipartBodyPublisher` itself to get notified of part changes. Will see what I can do.

Thanks for the suggestion!

**Comment by nemphys** [comment]
Thanks for this, a new release would be greatly appreciated.

**Comment by mizosoft** [comment]
I wanted to consider a RateLimiter for 1.4 but not yet sure, will see in about 3~4 days. In the meantime you can use `1.4-SNAPSHOT` for this feature.
