### ISSUE TITLE
Deflate decoder doesn't handle raw deflate streams that aren't zlib-wrapped 

### ISSUE THREAD

**Issue by insticore** [mizosoft/methanol#25]
I use MoreBodyHandlers.decoding(BodyHandlers.ofString()), but it fails because 'nowrap' is not enabled for inflating. Could you please explain how to use the decoder with this option?

**Comment by mizosoft** [comment]
Hi @insticore 

Could you tell me what `Content-Encoding` the server uses? The decoder enables 'nowrap' only for `gzip` as it has it's own wrapping method which is handled by the decoder. `deflate` however is expected to be zlib-wrapped to the `nowrap` option is not used. I'm guessing you're hit by something like [this](https://stackoverflow.com/questions/3932117/handling-http-contentencoding-deflate) where the server sends raw zlib bytes without the zlib-wrapping. Could you confirm that?

**Comment by mizosoft** [comment]
It is the case then that the server sends a stream of raw zlib bytes for `deflate`. The best fix to this is to make `DeflateDecoder` auto-detect such streams and handle both wrapped and unwrapped cases. I'll make the necessary changes soon. Thanks for reporting!
