### ISSUE TITLE
Feature: Add "sized" body publisher

### ISSUE THREAD

**Issue by gpsfl** [mizosoft/methanol#30]
Sometimes you want to provide a body publisher which can't automatically determine the size (ofInputStream for example), however you know the size of the stream through meta data or similar. For such cases it would be great to have a body publisher to which you can manually provide a content length. Something like:

```java
public class SizedBodyPublisher implements HttpRequest.BodyPublisher {
    private final HttpRequest.BodyPublisher delegate;
    private final int length;

    public SizedBodyPublisher(HttpRequest.BodyPublisher delegate, int length) {
        this.delegate = delegate;
        this.length = length;
    }

    @Override
    public long contentLength() {
        return length;
    }

    @Override
    public void subscribe(Flow.Subscriber<? super ByteBuffer> subscriber) {
        delegate.subscribe(subscriber);
    }
}
```

which can be used with a method like `MoreBodyHandlers.withSize(delegate, length)`

**Comment by mizosoft** [comment]
Hi @gpsfl. 

I believe this is already possible with JDK's `BodyPublishers`.

```java
var sizedBodyPublisher = BodyPublishers.fromPublisher(BodyPublishers.ofInputStream(() -> null), contentLength);
```

Isn't this what you're suggesting?

**Comment by gpsfl** [comment]
Oh, you're right. The naming might be a bit counter intuitive there. Thanks a lot!
