### ISSUE TITLE
Headers behavior in ResponseBuilder

### ISSUE THREAD

**Issue by regbo** [mizosoft/methanol#55]
I'm moving some code over from OkHttp and had a gotcha moment today that ate up a lot of my day. Out client was sending multiple copys of request headers and we couldn't figire it out.

In the ResponseBuilder class "headers" is used for **adding** headers. However, in other parts of the same class, methods with no prefixes are used for **setting** values. For example version(v) is used for setting.

I understand that there is a setHeader method for the headers, but I would recommend flip flopping the behavior to make it more intuitive. I think the "no-prefix" methods should be for setting, with "add" prefix methods used for adding. For example:

Current com.github.mizosoft.methanol.internal.extensions.ResponseBuilder:

```java
 public ResponseBuilder<T> header(String name, String value) {
    headersBuilder.add(name, value);
    return this;
  }

  public ResponseBuilder<T> setHeader(String name, String value) {
    headersBuilder.set(name, value);
    return this;
  }

  public ResponseBuilder<T> headers(HttpHeaders headers) {
    headersBuilder.addAll(headers);
    return this;
  }

```

Suggested com.github.mizosoft.methanol.internal.extensions.ResponseBuilder:

```java
  public ResponseBuilder<T> header(String name, String value) {
    headersBuilder.set(name, value);
    return this;
  }

  public ResponseBuilder<T> addHeader(String name, String value) {
    headersBuilder.add(name, value);
    return this;
  }
  
  public ResponseBuilder<T> headers(HttpHeaders headers) {
    clearHeaders();
    addHeaders(headers);
    return this;
  }

  public ResponseBuilder<T> addHeaders(HttpHeaders headers) {
    headersBuilder.addAll(headers);
    return this;
  }
```

This primarily came about because we are used to OkHttp client which uses the following logic for setting all headers:

```java
    /** Removes all headers on this builder and adds {@code headers}. */
    public Builder headers(Headers headers) {
      this.headers = headers.newBuilder();
      return this;
    }

```

**Comment by regbo** [comment]
Eh... I take it back, it looks like the default JDK Http client uses the behavior your library uses. Sorry about that.

**Comment by mizosoft** [comment]
I see. Rewriting/modifying responses is a common use case for interceptors, and `ResponseBuilder` is certainly useful for such purpose. I will open another issue to track moving `ResponseBuilder` to public API.
