### ISSUE TITLE
Jaxb Jakarta support

### ISSUE THREAD

**Issue by MarkusWendorf** [mizosoft/methanol#65]
Hey happy holidays,

I tried using the Jaxb Adapter with Java 21 using Jaxb Jakarta (`jakarta.xml.bind.annotation`) annotated classes but get a `UnsupportedOperationException`.

I assume the problem is that the Jaxb adapter still uses the Java 8 `javax.xml` namespace.

Not sure how to handle this properly but I think one could just copy & paste the existing adapter and change the imports and provide it as `jaxb-jakarta` adapter.

**Comment by mizosoft** [comment]
Hey @MarkusWendorf, thanks for reporting. Apologies for the late reply. 

Good catch. Creating a new adapter seems to be the right thing to do.
