### ISSUE TITLE
Methanol should implement newWebSocketBuilder

### ISSUE THREAD

**Issue by gpsfl** [mizosoft/methanol#93]
The default java `HttpClient` implements the `newWebSocketBuilder` method, but the `Methanol` client doesn't. I believe the `Methanol` client should always forward the method to the underlying client.

```java
Methanol.create().newWebSocketBuilder() // Throws an exception
Methanol.create().underlyingClient().newWebSocketBuilder() // This works
```

**Comment by gpsfl** [comment]
Do you have any plans for a new update with the changes in it?

**Comment by mizosoft** [comment]
Yes, will include it in the long-awaited `1.8.0` update. Currently finalizing the last two planned "new" features for this release (Hints API for adapters & Kotlin extensions).
